### ISSUE TITLE
psCompose Product Requirements Document

### ISSUE THREAD

**Issue by sartaj10** [perfsonar/pscompose#5]
Link - https://docs.google.com/document/d/1Vju1w3D-_ZcThfIypH04tUoj5oxxkN9Dl5CFHZLAxS4/edit#heading=h.ychgvzn268jr

**Comment by mfeit-internet2** [comment]
Would it be worth converting this document to Markdown and storing it as part of this repository?

**Comment by sartaj10** [comment]
Here it is - https://github.com/perfsonar/pscompose/blob/main/docs/requirements.md
